# Generated by Django 5.1.1 on 2024-10-01 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Train",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("train_id", models.CharField(max_length=100, unique=True)),
                ("location", models.CharField(max_length=100)),
                ("direction", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("time", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="TrainDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.CharField(max_length=100)),
                ("image_link", models.URLField()),
                (
                    "train",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="train_app.train",
                    ),
                ),
            ],
        ),
    ]
