# Generated by Django 5.1.1 on 2024-10-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("train_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="train",
            name="train_id",
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
